services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=${PYTHON_VERSION:-3.12}
    hostname: workspace
    environment:
      - PORTAINER_URL=${PORTAINER_URL}
      - KUBECONFIG=/secrets/.kubeconfig
    volumes:
      - .:/app:ro
      - secrets:/secrets

volumes:
  secrets:
