services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=${PYTHON_VERSION:-3.12}
    environment:
      - PORTAINER_URL=${PORTAINER_URL}
    volumes:
      - ./.token:/root/.token:ro
      - ./scripts:/scripts:ro
